name: Deploy Cloudflare

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "dist/**"
      - "functions/**"
      - ".github/workflows/deploy-cloudflare-pages.yml"
      - "wrangler.toml"
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy official website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: deploy

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: pages deploy dist --project-name=yiyuwebsite --branch=${{ github.ref_name }} --commit-dirty=true
